[tools]
node = "25"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:doctoc" = "latest"
"npm:eslint" = "latest"
ruby = "3.4.7"
"npm:prettier" = "latest"
go = "1.25"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node", "go"]
